# Custom Language File for Launcher Customizer

[ejs.app]
title = "NMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/NMC-Network/NMCLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/NMC-Network/NMCLauncher"
supportLink = "https://github.com/NMC-Network/NMCLauncher/issues"

[ejs.welcome]
welcomeHeader = "ようこそ、NMC Launcherへ！"
welcomeDescription = "このランチャーを使えば、簡単かつ素早くNovaMCに参加できます。面倒な設定は一切不要。"
welcomeDescCTA = "数クリックでサーバーに参加し、最高なカジノライフを始めましょう。"
